create table if not exists staff_users (
  id bigint generated by default as identity primary key,
  full_name text not null,
  username text not null unique,
  password_hash text not null,
  role text not null check (role in ('admin', 'staff')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists rooms (
  id bigint generated by default as identity primary key,
  room_number text not null unique,
  room_type text not null,
  capacity integer not null default 1,
  status text not null check (status in ('vacant', 'occupied', 'maintenance')),
  created_at timestamptz not null default now()
);

create table if not exists guests (
  id bigint generated by default as identity primary key,
  full_name text not null,
  age integer not null,
  contact text,
  email text,
  created_at timestamptz not null default now()
);

create table if not exists bookings (
  id bigint generated by default as identity primary key,
  guest_id bigint not null references guests(id) on delete cascade,
  room_id bigint not null references rooms(id) on delete restrict,
  check_in timestamptz not null,
  check_out timestamptz not null,
  stay_hours integer not null default 3,
  pax integer not null default 1,
  status text not null check (status in ('reserved', 'checked_in', 'checked_out', 'cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists bookings_room_id_idx on bookings(room_id);
create index if not exists bookings_guest_id_idx on bookings(guest_id);

create table if not exists approval_requests (
  id bigint generated by default as identity primary key,
  request_type text not null check (request_type in ('guest_delete', 'booking_delete')),
  entity_id bigint not null,
  requested_by bigint not null references staff_users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  notes text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists approval_requests_status_idx on approval_requests(status);
